name: Build Dev Preview

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'help/**'
      - '**/build-site.yml'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Solution_Name: Razor.sln       

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Razor
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Set AssemblyInfo
      uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
      with:                     
        version: '1.10.${{ github.run_number }}.0'

    - name: Build Razor (x86)
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration /p:Platform="Any CPU"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build Razor (x64)
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration /p:Platform=x64
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Archive Razor x86 build artifacts      
      run: |
        cd bin/Win32/Release/
        7z a -tzip "Razor-dev-x86-preview.zip" "*"

    - name: Archive Razor x64 build artifacts      
      run: |
        cd bin/x64/Release/
        7z a -tzip "Razor-dev-x64-preview.zip" "*"

    - name: Delete Dev Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: Razor-dev-preview
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Dev Release
      uses: ncipollo/release-action@v1
      with:
        name: "Razor Dev Preview"
        body: "This is built automatically after each commit to master, so it may contain bugs and/or unfinished features but is generally considered stable. Use at your own risk."
        artifacts: "bin/Win32/Release/Razor-dev-x86-preview.zip,bin/x64/Release/Razor-dev-x64-preview.zip"          
        prerelease: true
        tag: Razor-dev-preview
        token: ${{ secrets.GITHUB_TOKEN }}

